### ISSUE TITLE
Type of y_out

### ISSUE THREAD

**Issue by hombit** [JuliaLang/ODE.jl#78]
Why type of y_out is Array{Array{T,1},1}? Maybe it should be 2-D array: Array{T,2}?

**Comment by tlycken** [comment]
This was a concious decision based on discussions [here](https://github.com/JuliaLang/ODE.jl/issues/20) and in other places. Basically, it's because the type of `y0` could potentially be any type that supports a few basic mathematical operations, and not just scalar `Number`s or vectors. In other words, there's no guarantee that `y_out` would fit in an `Array{T,2}`.

You can always get the matrix form by using `hcat(y_out...)` if that's important for you in the next step.

**Comment by hombit** [comment]
Thank you for the fast answer!
